{-
   Todo

   Todo

   OpenAPI Version: 3.0.3
   Todo API version: 1.0.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Todo.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module Todo.Logging
  ( module Todo.LoggingKatip
  ) where

import Todo.LoggingKatip

#else

module Todo.Logging
  ( module Todo.LoggingMonadLogger
  ) where

import Todo.LoggingMonadLogger

#endif
